version: "3.7"

services:
  sprout:
    build:
      context: .
      target: build
    ports:
      - "8080:8080"
    environment:
      PSQL_HOST: sprout
      PSQL_PORT: 5432
      PSQL_NAME: sprout
      PSQL_USER: sprout
      PSQL_PASSWORD: sprout


  sprout-db:
    image: postgres:15.1
    container_name: sprout-db
    environment:
      POSTGRES_USER: sprout
      POSTGRES_PASSWORD: sprout
      POSTGRES_DB: sprout
    ports:
      - "5432:5432"

